// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent/dialect/sql"
	"github.com/pigfall/pf_ent_proto_demo/ent/dept"
)

// Dept is the model entity for the Dept schema.
type Dept struct {
	config
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the DeptQuery when eager-loading is set.
	Edges DeptEdges `json:"edges"`
}

// DeptEdges holds the relations/edges for other nodes in the graph.
type DeptEdges struct {
	// User holds the value of the user edge.
	User []*User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading.
func (e DeptEdges) UserOrErr() ([]*User, error) {
	if e.loadedTypes[0] {
		return e.User, nil
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Dept) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case dept.FieldID:
			values[i] = new(sql.NullString)
		default:
			return nil, fmt.Errorf("unexpected column %q for type Dept", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Dept fields.
func (d *Dept) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case dept.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				d.ID = value.String
			}
		}
	}
	return nil
}

// QueryUser queries the "user" edge of the Dept entity.
func (d *Dept) QueryUser() *UserQuery {
	return (&DeptClient{config: d.config}).QueryUser(d)
}

// Update returns a builder for updating this Dept.
// Note that you need to call Dept.Unwrap() before calling this method if this Dept
// was returned from a transaction, and the transaction was committed or rolled back.
func (d *Dept) Update() *DeptUpdateOne {
	return (&DeptClient{config: d.config}).UpdateOne(d)
}

// Unwrap unwraps the Dept entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (d *Dept) Unwrap() *Dept {
	tx, ok := d.config.driver.(*txDriver)
	if !ok {
		panic("ent: Dept is not a transactional entity")
	}
	d.config.driver = tx.drv
	return d
}

// String implements the fmt.Stringer.
func (d *Dept) String() string {
	var builder strings.Builder
	builder.WriteString("Dept(")
	builder.WriteString(fmt.Sprintf("id=%v", d.ID))
	builder.WriteByte(')')
	return builder.String()
}

// Depts is a parsable slice of Dept.
type Depts []*Dept

func (d Depts) config(cfg config) {
	for _i := range d {
		d[_i].config = cfg
	}
}
